---
volumes:
  pgdata: {}
  redis: {}

services:
  postgres:
    env_file: .env
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER:-blogi}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-blogi}
      POSTGRES_DATABASE: ${DB_NAME:-blogi}
      PGDATA: /data
    volumes:
      - pgdata:/data
    ports:
      - 5432:5432

  redis:
    env_file: .env
    image: redis:8
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis:/data
