// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `moe.hayden.blogi.actor.getProfile` namespace.
pub const NSID: &str = "moe.hayden.blogi.actor.getProfile";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Handle or DID of account to fetch profile of.
    pub actor: atrium_api::types::string::AtIdentifier,
}
pub type Parameters = atrium_api::types::Object<ParametersData>;
pub type Output = crate::moe::hayden::blogi::actor::defs::ProfileViewDetailed;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
