// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `moe.hayden.blogi.actor.profile` namespace.
use atrium_api::types::TryFromUnknown;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///Small image to be displayed next to posts from account. AKA, 'profile picture'
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub avatar: core::option::Option<atrium_api::types::BlobRef>,
    ///Larger horizontal image to display behind profile view.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub banner: core::option::Option<atrium_api::types::BlobRef>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub created_at: core::option::Option<atrium_api::types::string::Datetime>,
    ///Free-form profile description text.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub description: core::option::Option<String>,
    pub display_name: String,
}
pub type Record = atrium_api::types::Object<RecordData>;
impl From<atrium_api::types::Unknown> for RecordData {
    fn from(value: atrium_api::types::Unknown) -> Self {
        Self::try_from_unknown(value).unwrap()
    }
}
