// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `moe.hayden.blogi.blog` namespace.
pub mod comment;
pub mod defs;
pub mod entry;
pub mod get_entries_for_author;
#[derive(Debug)]
pub struct Comment;
impl atrium_api::types::Collection for Comment {
    const NSID: &'static str = "moe.hayden.blogi.blog.comment";
    type Record = comment::Record;
}
#[derive(Debug)]
pub struct Entry;
impl atrium_api::types::Collection for Entry {
    const NSID: &'static str = "moe.hayden.blogi.blog.entry";
    type Record = entry::Record;
}
