// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `moe.hayden.blogi.blog.defs` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PostViewData {
    pub author: crate::moe::hayden::blogi::actor::defs::ProfileView,
    pub cid: atrium_api::types::string::Cid,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub comment_count: core::option::Option<i64>,
    pub indexed_at: atrium_api::types::string::Datetime,
    pub record: PostViewRecord,
    pub uri: String,
}
pub type PostView = atrium_api::types::Object<PostViewData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PostViewRecordData {
    pub content: String,
    pub created_at: atrium_api::types::string::Datetime,
    pub title: String,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub updated_at: core::option::Option<atrium_api::types::string::Datetime>,
}
pub type PostViewRecord = atrium_api::types::Object<PostViewRecordData>;
