// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!A collection of known record types.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum KnownRecord {
    #[serde(rename = "moe.hayden.blogi.actor.profile")]
    MoeHaydenBlogiActorProfile(Box<crate::moe::hayden::blogi::actor::profile::Record>),
    #[serde(rename = "moe.hayden.blogi.blog.comment")]
    MoeHaydenBlogiBlogComment(Box<crate::moe::hayden::blogi::blog::comment::Record>),
    #[serde(rename = "moe.hayden.blogi.blog.entry")]
    MoeHaydenBlogiBlogEntry(Box<crate::moe::hayden::blogi::blog::entry::Record>),
}
impl From<crate::moe::hayden::blogi::actor::profile::Record> for KnownRecord {
    fn from(record: crate::moe::hayden::blogi::actor::profile::Record) -> Self {
        KnownRecord::MoeHaydenBlogiActorProfile(Box::new(record))
    }
}
impl From<crate::moe::hayden::blogi::actor::profile::RecordData> for KnownRecord {
    fn from(record_data: crate::moe::hayden::blogi::actor::profile::RecordData) -> Self {
        KnownRecord::MoeHaydenBlogiActorProfile(Box::new(record_data.into()))
    }
}
impl From<crate::moe::hayden::blogi::blog::comment::Record> for KnownRecord {
    fn from(record: crate::moe::hayden::blogi::blog::comment::Record) -> Self {
        KnownRecord::MoeHaydenBlogiBlogComment(Box::new(record))
    }
}
impl From<crate::moe::hayden::blogi::blog::comment::RecordData> for KnownRecord {
    fn from(record_data: crate::moe::hayden::blogi::blog::comment::RecordData) -> Self {
        KnownRecord::MoeHaydenBlogiBlogComment(Box::new(record_data.into()))
    }
}
impl From<crate::moe::hayden::blogi::blog::entry::Record> for KnownRecord {
    fn from(record: crate::moe::hayden::blogi::blog::entry::Record) -> Self {
        KnownRecord::MoeHaydenBlogiBlogEntry(Box::new(record))
    }
}
impl From<crate::moe::hayden::blogi::blog::entry::RecordData> for KnownRecord {
    fn from(record_data: crate::moe::hayden::blogi::blog::entry::RecordData) -> Self {
        KnownRecord::MoeHaydenBlogiBlogEntry(Box::new(record_data.into()))
    }
}
impl Into<atrium_api::types::Unknown> for KnownRecord {
    fn into(self) -> atrium_api::types::Unknown {
        atrium_api::types::TryIntoUnknown::try_into_unknown(&self).unwrap()
    }
}
